# Antarctic Ecosystem Simulation Configuration

simulation_metadata:
  device: 'cpu'  # Change to 'cuda' if GPU available
  num_episodes: 1
  num_steps_per_episode: 30
  num_substeps_per_step: 4
  calibration: false
  visualize: true

  # Antarctica grid size
  max_x: 100
  max_y: 100
  
  # Penguin and Seal population
  num_predators: 1000  # Leopard seals
  num_prey: 9000       # Emperor penguins
  num_grass: 5000      # Krill/fish patches (food sources)

  # Environmental parameters
  temperature: -20     # Average temperature in Celsius
  wind_speed: 30       # Wind speed in km/h

state:
  environment:
    bounds:
      name: 'Antarctica Region Bounds'
      learnable: false
      shape: 2
      dtype: 'int'
      value:
        - ${simulation_metadata.max_x}
        - ${simulation_metadata.max_y}
      initialization_function: null

  agents:
    predator:  # Leopard Seals
      number: ${simulation_metadata.num_predators}
      properties:
        coordinates:
          name: 'Position'
          learnable: false
          shape:
            - ${state.agents.predator.number}
            - 2
          dtype: 'int'
          initialization_function:
            generator: 'random_int'
            arguments:
              lower_limit:
                name: 'Lower Bound'
                learnable: false
                shape:
                  - 1
                value: 0
                initialization_function: null
              upper_limit:
                name: 'Upper Bound'
                learnable: false
                shape:
                  - 1
                value: 
                  - ${simulation_metadata.max_x}
                  - ${simulation_metadata.max_y}
                initialization_function: null
        energy:
          name: 'Energy'
          learnable: false
          shape:
            - ${state.agents.predator.number}
            - 1
          dtype: 'float'
          initialization_function:
            generator: 'random_float'
            arguments:
              lower_limit:
                name: 'Lower Bound'
                learnable: false
                shape:
                  - 1
                value: 50
                initialization_function: null
              upper_limit:
                name: 'Upper Bound'
                learnable: false
                shape:
                  - 1
                value: 100
                initialization_function: null
        stride_work:
          name: 'Energy Lost in Taking One Step'
          learnable: true
          shape:
            - 1
          dtype: 'float'
          value: 1
          initialization_function: null
    prey:  # Emperor Penguins
      number: ${simulation_metadata.num_prey}
      properties:
        coordinates:
          name: 'Position'
          learnable: false
          shape:
            - ${state.agents.prey.number}
            - 2
          dtype: 'int'
          initialization_function:
            generator: 'random_int'
            arguments:
              lower_limit:
                name: 'Lower Bound'
                learnable: false
                shape:
                  - 1
                value: 0
                initialization_function: null
              upper_limit:
                name: 'Upper Bound'
                learnable: false
                shape:
                  - 1
                value: 
                  - ${simulation_metadata.max_x}
                  - ${simulation_metadata.max_y}
                initialization_function: null
        energy:
          name: 'Energy'
          learnable: false
          shape:
            - ${state.agents.prey.number}
            - 1
          dtype: 'float'
          initialization_function:
            generator: 'random_float'
            arguments:
              lower_limit:
                name: 'Lower Bound'
                learnable: false
                shape:
                  - 1
                value: 40
                initialization_function: null
              upper_limit:
                name: 'Upper Bound'
                learnable: false
                shape:
                  - 1
                value: 100
                initialization_function: null
        stride_work:
          name: 'Energy Lost in Taking One Step'
          learnable: true
          shape:
            - 1
          dtype: 'float'
          value: 5
          initialization_function: null
        nutritional_value:
          name: 'Energy Gained Upon Consuming Prey'
          learnable: true
          shape:
            - 1
          dtype: 'float'
          value: 20
          initialization_function: null

  objects:
    grass:  # Krill/Fish
      number: ${simulation_metadata.num_grass}
      properties:
        coordinates:
          name: 'Position'
          learnable: false
          shape:
            - ${state.objects.grass.number}
            - 2
          dtype: 'int'
          initialization_function:
            generator: 'random_int'
            arguments:
              lower_limit:
                name: 'Lower Bound'
                learnable: false
                shape:
                  - 1
                value: 0
                initialization_function: null
              upper_limit:
                name: 'Upper Bound'
                learnable: false
                shape:
                  - 1
                value: 
                  - ${simulation_metadata.max_x}
                  - ${simulation_metadata.max_y}
                initialization_function: null
        growth_stage:
          name: 'The Growth Stage'
          learnable: false
          shape:
            - ${state.objects.grass.number}
            - 1
          dtype: 'int'
          initialization_function:
            generator: 'random_int'
            arguments:
              lower_limit:
                name: 'Lower Bound'
                learnable: false
                shape:
                  - 1
                value: 0
                initialization_function: null
              upper_limit:
                name: 'Upper Bound'
                learnable: false
                shape:
                  - 1
                value: 1
                initialization_function: null
        regrowth_time:
          name: 'Time for Food to Replenish'
          learnable: true
          shape:
            - 1
          dtype: 'float'
          value: 20  # Faster replenishment for demo
          initialization_function: null
        growth_countdown:
          name: 'Time for Food to Grow Fully'
          learnable: false
          shape:
            - ${state.objects.grass.number}
            - 1
          dtype: 'float'
          initialization_function:
            generator: 'random_float'
            arguments:
              lower_limit:
                name: 'Lower Bound'
                learnable: false
                shape:
                  - 1
                value: 0
                initialization_function: null
              upper_limit:
                name: 'Upper Bound'
                learnable: false
                shape:
                  - 1
                value: 20
                initialization_function: null
        nutritional_value:
          name: 'Energy Gained Upon Consuming Food'
          learnable: true
          shape:
            - 1
          dtype: 'float'
          value: 7
          initialization_function: null

  network:
    agent_agent:
      predator_prey:
        type: 'grid'
        arguments:
          shape:
            - ${simulation_metadata.max_x}
            - ${simulation_metadata.max_y}

substeps:
  '0':
    name: 'Move'
    description: 'Penguin and Seal Movement'
    active_agents:
      - 'predator'
      - 'prey'
    observation:
      predator:
        find_neighbors:
          generator: 'FindNeighbors'
          arguments: null
          input_variables:
            bounds: 'environment/bounds'
            adj_grid: 'network/agent_agent/predator_prey/adjacency_matrix'
            positions: 'agents/predator/coordinates'
          output_variables:
            - possible_neighbors
      prey:
        find_neighbors:
          generator: 'FindNeighbors'
          arguments: null
          input_variables:
            bounds: 'environment/bounds'
            adj_grid: 'network/agent_agent/predator_prey/adjacency_matrix'
            positions: 'agents/prey/coordinates'
          output_variables:
            - possible_neighbors
    policy:
      predator:
        decide_movement:
          generator: 'DecideMovement'
          arguments: null
          input_variables:
            positions: 'agents/predator/coordinates'
            energy: 'agents/predator/energy'
          output_variables:
            - next_positions
      prey:
        decide_movement:
          generator: 'DecideMovement'
          arguments: null
          input_variables:
            positions: 'agents/prey/coordinates'
            energy: 'agents/prey/energy'
          output_variables:
            - next_positions
    transition:
      update_positions:
        generator: 'UpdatePositions'
        arguments: null
        input_variables:
          prey_pos: 'agents/prey/coordinates'
          prey_energy: 'agents/prey/energy'
          pred_pos: 'agents/predator/coordinates'
          pred_energy: 'agents/predator/energy'
          prey_work: 'agents/prey/stride_work'
          pred_work: 'agents/predator/stride_work'
        output_variables:
          - prey_pos
          - prey_energy
          - pred_pos
          - pred_energy
  '1':
    name: 'Eat'
    description: 'Penguin Foraging'
    active_agents:
      - 'prey'
    observation:
      prey: null
    policy:
      prey:
        find_eatable_grass:
          generator: 'FindEatableGrass'
          arguments: null
          input_variables:
            bounds: 'environment/bounds'
            positions: 'agents/prey/coordinates'
            grass_growth: 'objects/grass/growth_stage'
          output_variables:
            - eatable_grass_positions
    transition:
      eat_grass:
        generator: 'EatGrass'
        arguments: null
        input_variables:
          energy: 'agents/prey/energy'
          grass_growth: 'objects/grass/growth_stage'
          growth_countdown: 'objects/grass/growth_countdown'
          bounds: 'environment/bounds'
          prey_pos: 'agents/prey/coordinates'
          nutrition: 'objects/grass/nutritional_value'
          regrowth_time: 'objects/grass/regrowth_time'
        output_variables:
          - energy
          - grass_growth
          - growth_countdown
  '2':
    name: 'Hunt'
    description: 'Seal Predation'
    active_agents:
      - 'predator'
    observation:
      predator: null
    policy:
      predator:
        find_targets:
          generator: 'FindTargets'
          arguments: null
          input_variables:
            prey_pos: 'agents/prey/coordinates'
            pred_pos: 'agents/predator/coordinates'
          output_variables:
            - target_positions
    transition:
      hunt_prey:
        generator: 'HuntPrey'
        arguments: null
        input_variables:
          prey_energy: 'agents/prey/energy'
          pred_energy: 'agents/predator/energy'
          nutritional_value: 'agents/prey/nutritional_value'
          prey_pos: 'agents/prey/coordinates'
          pred_pos: 'agents/predator/coordinates'
        output_variables:
          - prey_energy
          - pred_energy
  '3':
    name: 'Grow'
    description: 'Food Source Replenishment'
    active_agents:
      - 'prey'
    observation:
      prey: null
    policy:
      prey: null
    transition:
      grow_grass:
        generator: 'GrowGrass'
        arguments: null
        input_variables:
          grass_growth: 'objects/grass/growth_stage'
          growth_countdown: 'objects/grass/growth_countdown'
        output_variables:
          - grass_growth
          - growth_countdown